### ISSUE TITLE
Step #8 in the Install Procedure

### ISSUE THREAD

**Issue by Bob-Bradley** [lithnet/resourcemanagement-webservice#1]
Ryan,  Great tool and having a play for the first time with this over the weekend.
This is not a bug report - rather a pointer to something I spun my wheels on for about an hour ... looking for the "Isapi + CGI Restrictions" icon on the RMWS website when it was actually to be found on the server node.  There I was thinking I was missing a prerequisite component of IIS 7.5 ... until I found this thread: http://forums.iis.net/t/1133028.aspx?ISAPI+CGI+Restriction+configuration+missing

**Comment by ryannewington** [comment]
Good point, it's not very clear.

What about this text instead?

```
8. Navigate back to the top-level web server node, and configure the ISAPI and CGI Restrictions feature to allow ASP.NET v4.0
```

**Comment by Bob-Bradley** [comment]
That would do it @ryannewington :)
