### ISSUE TITLE
Update to install guide

### ISSUE THREAD

**Issue by Bob-Bradley** [lithnet/resourcemanagement-webservice#10]
Hi Ryan - absolutely awesome work - can't wait to get down and dirty with this now!  One extra step I had to do after the install was to change the application pool to a local AD account (and add it to the necessary IIS_IUSRS group), then restart.  If I don't do that then only the HELP page works and I get what appear to be delegation issues.  Did I miss something?

**Comment by ryannewington** [comment]
Hey @Bob-Bradley 

If you are using integrated windows auth, then quite possibly. The steps shown should work for basic auth. Do we need to enhance the guide for other auth types?

**Comment by Bob-Bradley** [comment]
Ah you're quite correct - the key to getting this working was actually to change the app pool from INTEGRATED to CLASSIC.  It's now working as the default ApplicationPoolIdentity.
