### ISSUE TITLE
"Http or Https" on web.config file??

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-webservice#16]
I am looking into the steps for installing the web service I have a question on step 10.

<lithnetResourceManagementClientresourceManagementServiceBaseAddress="http://localhost:5725"/>

Is that supposed to be Https in the web.config file when I am trying to install in the FIM server. or it should be the same Http??? 

If it should be Http only, will there be a secured connection for the API call can you help me with this. I did my research but did find  convincing answer on this.

Thank you!

**Comment by ryannewington** [comment]
It's http. That's not something specific to my web service, the portal, sync engine, etc, all use http. The fim service doesn't support https. However, all data is encrypted and signed using the built in WCF soap encryption capability. So it's secure, just using a different mechanism other than TLS.
