### ISSUE TITLE
Get Resource based on attribute value

### ISSUE THREAD

**Issue by nishitm** [lithnet/resourcemanagement-webservice#17]
Hi,

Is there any way to search the resource based on some attribute value using API?
I have gone through the documentations but not able to find.

Any help is appreciated

**Comment by ryannewington** [comment]
Hi @nishitm,

There are two methods

You can use a standard FIM XPath query using the following query
https://github.com/lithnet/resourcemanagement-webservice/wiki/Search-for-resources-(v2)
You'll need to URL encode the xpath itself, so a query for the person with the account name of ryan (/Person[AccountName='ryan']) will be 
```/v2/resources/?filter=%2FPerson%5BAccountName%3D%27ryan%27%5D```

If you want to get based on a unique anchor attribute (such as account Name)
https://github.com/lithnet/resourcemanagement-webservice/wiki/Get-a-resource-(v2)

```/v2/resources/Person/AccountName/ryan```

**Comment by nishitm** [comment]
Thanks 👍
