### ISSUE TITLE
Bulk Updates

### ISSUE THREAD

**Issue by Celticview** [lithnet/resourcemanagement-webservice#18]
Is it possible to send bulk requests to the API for example can I send a batch of user creates or updates in one request?

If so what is the format of the JSON that is required and are there any other parameters that need to be supplied?

**Comment by ryannewington** [comment]
Hi @celticview,

Unfortunately not. Composite requests aren't supported by this API. They are supported by the .net client library if that is an option for you

Ryan

**Comment by Celticview** [comment]
OK thanks Ryan. We will look into it. It isn't a show stopper but would have been a nice to have for some bulk changes we had to make but they are not frequent so PS was able to upload the JSON we pulled from MIM via the API and modified.

But we will check the .net client library as an option.

Thanks
CV

**Comment by ryannewington** [comment]
If by PS you mean powershell, then you can use the native PowerShell module which has built-in support for composite updates. Put all your changed ResourceObjects into an array and call `Save-Resource`

https://github.com/lithnet/resourcemanagement-powershell/wiki/Save-Resource

**Comment by Celticview** [comment]
Yes that is exactly the type of thing we were planning to do. Thanks
