### ISSUE TITLE
Help Needed: How to get Disp

### ISSUE THREAD

**Issue by cinguva** [lithnet/resourcemanagement-webservice#19]
I am using XPATH query in my web service to get data from MIM. 
For Person Object, i need to get Manager attribute with DisplayName instead of GUID

Here is my Web Service call
GET /v1/resources/?filter=/Person[(WorkerStatus='Active') and (EmployeeType='Employee')]&attributes=EmployeeType,DisplayName,Manager

While using FIM Query tool : i could use Manager.DisplayName to have DisplayName instead of GUID

Do we have something similar ?

**Comment by ryannewington** [comment]
Shouldn't your Xpath be `/Person[(WorkerStatus='Active') and (EmployeeType='Employee')]/Manager`

But do note, that you can't get attributes from both the person and it's manager at the same time. This is a FIM/Xpath limitation. Your query must return a reference object (either the person OR or their manager). Only then can you specify what attributes you want from that referenced object.
