### ISSUE TITLE
Powershell script for REST API call

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-webservice#22]
Hello,

We are using the Lithnet REST API service and all the operations are working fine when I invoke from the postman or SOAP UI, etc. If I try a GET request using the PowerShell with Basic AUTH, it fails with an invalid credential error, I tried all different ways to do a GET query from PowerShell but nothing worked. Is there any authentication issues for using PowerShell? or do you have any examples for GET request using PowerShell?

Appreciate your help.

Thank you

**Comment by ryannewington** [comment]
@darrenjrobinson have you done this before?

@kongarasri have you considered using the native powershell module? https://github.com/lithnet/resourcemanagement-powershell

**Comment by kongarasri** [comment]
Yeah, I tried the PowerShell module. But the problem was we have to install the Lithnet.ResourceManagement.Automation.msi for that and the script we are working on will run on 100's of servers across the globe so we don't want to try that approach. 

I really appreciate your quick response for issues and help.

Thank you.

**Comment by ryannewington** [comment]
You can install from Powershell gallery if that is an option Install-Module -Name LithnetRMA 

Can you post the code you are using to do the get operation?

**Comment by darrenjrobinson** [comment]
Yes, I use this a lot. 
You need to specify the Username as Domain\User
I have an example here https://blog.darrenjrobinson.com/getting-started-with-the-lithnet-rest-api-for-the-microsoft-identity-manager-service/

**Comment by kongarasri** [comment]
I am using the below script to do a GET call from PowerShell:

#$basicAuthValue = "Basic $base64AuthInfo"
#$Cred=Get-Credential
$basicAuthValue = ""
 
$header = @{
"Content-Type"="application/x-www-form-urlencoded"
"Authorization" = "$basicAuthValue" 
}
  
$url=""  
 
$response1=Invoke-RestMethod -Uri $url -Method GET -Headers $header #-Credential $Cred 
$i=$response1 | ConvertTo-Json 


I also tried the @darrenjrobinson code from https://blog.darrenjrobinson.com/getting-started-with-the-lithnet-rest-api-for-the-microsoft-identity-manager-service/
Still the same issue. 

The only response I get using any code was "Access is denied due to invalid credentials". And it works from postman with the same credentials.

**Comment by kongarasri** [comment]
I got it working, I did some changes to the @darrenjrobinson code and it's working. Really appreciate you guys help.

Thank you
