### ISSUE TITLE
Cannot generate swagger file

### ISSUE THREAD

**Issue by bryanjager** [lithnet/resourcemanagement-webservice#23]
Hello Ryan, this is a great solution it has helped us greatly.  I am encountering an issue.  We need to generate the swagger file, but I cannot seem to figure it out.  I tried https://localhost:port/api-docs/, https://localhost:port/api-docs/swagger.json and a few other combinations of v1/v2/resources/etc, but none seem to work.  

I checked out the SwaggerWCF project and tried to figure out how to generate the swagger.  It looks like all the swagger code is good, but it talks about an app.config file for self hosted, but I cannot seem to find one.  I was looking at: https://github.com/abelsilva/swaggerwcf.  Not sure if it is needed or not?

Sorry for the issue, but I am new to all of this.  I appreciate your assistance with generating the swagger file.

**Comment by ryannewington** [comment]
No, its not a setting you are missing. I remember now that impersonation is required for classic mode. I'm going to need more time with this. Can you use integrated mode to download your swagger.json file for now, and switch back to classic. I'll need to get deeper under the hood to try and find a solution where both work as expected
