### ISSUE TITLE
issue with Anchor Attribute search

### ISSUE THREAD

**Issue by sivabalaguru** [lithnet/resourcemanagement-webservice#25]
Hi,
I have been trying to search based on attribute and value as below:
https://restapi.contoso.com:643/v2/resources/Person/AccountName/john.doe

I have encountered with the below error.
![image](https://user-images.githubusercontent.com/15766653/78004735-28614100-7358-11ea-9ba3-92a6b5f122ad.png)

I could able to search with filter.

**Comment by KentNordstrom** [comment]
If the accountname has non-latin characters I think you need to html encode them in the url

**Comment by sivabalaguru** [comment]
Hi Kent,
AccountName doesn't have any non-latin characters. It just have normal alphabets with a dot. 

I did tried URL encoding the (dot) %2E . But still the same error.

**Comment by ryannewington** [comment]
IIS thinks you are trying to download a '.DOE' file.

Try adding in a URL handler into your web.config file for this path

https://stackoverflow.com/questions/11728846/dots-in-url-causes-404-with-asp-net-mvc-and-iis

Let me know how it goes

**Comment by sivabalaguru** [comment]
Hi Ryan,
It is not just about the dot. I did tried finding with Email. 
That didn't work too.
Let me try applying the web.config fix.

Siva Kumar

**Comment by sivabalaguru** [comment]
Seems like existing web.config already have this http handler.
<handlers>
        <add name="ApiURIs-ISAPI-Integrated-4.0" path="*" type="System.Web.Handlers.TransferRequestHandler" verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" preCondition="integratedMode,runtimeVersionv4.0" />
      </handlers>

    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
	      </handlers>

**Comment by ryannewington** [comment]
You need to keep those handlers in, and add the additional handler in the link in sent. It's a different module.

**Comment by sivabalaguru** [comment]
I did updated that in the handlers.

But No Luck.
`<handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="ApiURIs-ISAPI-Integrated-4.0" path="/resources/*" verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>`

**Comment by ryannewington** [comment]
I've done some testing on my own instances, and can't reproduce the error. Is there anything else on this web server? Something must be changing the handling of these requests somewhere along the line.

You can see in your original error message that the 'StaticFile' handler has picked up the request, rather than the web api.

**Comment by sivabalaguru** [comment]
Hi Ryan,

I have hosted this web service on the same server where MIM Portal is hosted.

Other API calls are working as expected except for this operation.

**Comment by ryannewington** [comment]
I'm wondering if there is something overriding this coming from the overall sharepoint/iis config. I'm not an expert in this space I'm afraid. All I know is that the call is not making it to the API. I run this Web service on the fim service itself. Perhaps you can try there or set up a dedicated server for this.
