### ISSUE TITLE
Authentication using Client secret

### ISSUE THREAD

**Issue by sivabalaguru** [lithnet/resourcemanagement-webservice#26]
Is there a way that we can change the authentication from Basic to token based using Client ID and Client Secret?
We would like to publish the API on the internet via App Proxy.

What would be best practice to secure the API?

**Comment by KentNordstrom** [comment]
I never set it up using Basic auth I always configure it to use Kerberos.
I then publish it using Azure Application Proxy to expose it using Azure Authentication.

You cannot use a Service Principal to make the call since that identity cannot be translated into a Kerberos token by the App Proxy. It needs to be an identity that can be translated.

And since the FIMService also needs to know the identity it needs to be an identity known by FIMService.

**Comment by sivabalaguru** [comment]
If it uses Azure Authentication, Can we integrate with Daemon processes based client applications?
The main concern of using a user account is that would need a password to be shared across the teams.

**Comment by ryannewington** [comment]
@KentNordstrom is spot on with how to do this by layering AAP on top of the web service. But as he said, at the end of the day, you still need a valid windows identity that the MIM service recognizes.

I wouldn't be implementing either creds or a clientid/secret in a client app. Both have the same problem which are essentially that you are sharing a password. The benefit of using the way Kent described is each you can authenticate with their own AAD credentials.

If you wanted something else, unfortunately you'd need to implement your own authentication and authorization logic over the top of the API.

**Comment by sivabalaguru** [comment]
I have deployed the API on the same server where MIM Portal is deployed but on a different port.
I did tried enabling Windows authentication with negotiate:kerberos and re-used the same App pool credentials configured for MIM Portal as it already have SPNs registered.

The App pool credentials already have Kerberos Constrained delegation configured for FIM Service.

It is now prompting credentials frequently and not letting me in. 

Did I miss any settings?

**Comment by ryannewington** [comment]
You'll need to set new SPN for the host and Port. Eg HTTP/myserver.com:8080

The existing SPN will not work if you have a non standard port

**Comment by sivabalaguru** [comment]
Thanks Ryan.. that worked fine...
If there are any daemon processes or background applications that would need to access MIM REST API, How would they need to authenticate AAD as it should be non-interactive?

**Comment by ryannewington** [comment]
@KentNordstrom Any ideas on this one?

**Comment by KentNordstrom** [comment]
In our solutions where Azure Functions call the API using Azure AD App Proxy we have the function get credentials from Azure KeyVault and then use those user credentials to call the API. This requires MFA exception for that identity when calling the API.

**Comment by KentNordstrom** [comment]
In theory (I have not had time to test this) any identity in Azure, including any Service Principal should be possible to be represented in on-prem AD for KCD to work. You need some property of the SP in Azure to match some property of the on-prem AD account to get KCD working. In that case we are not talking about UPN but likely the ObjectID in Azure AD or something that's available in the token handed over to the Azure Application Proxy endpoint.

**Comment by sivabalaguru** [comment]
> In our solutions where Azure Functions call the API using Azure AD App Proxy we have the function get credentials from Azure KeyVault and then use those user credentials to call the API. This requires MFA exception for that identity when calling the API.

Kent,

Do you have any code samples that authenticate Azure using Azure AD credentials?
Most of the non-interactive apps I see authenticates AAD using Client ID and Secret. 
Even with AAD authentication, Sign-In process is User interactive.

**Comment by KentNordstrom** [comment]
I'm not the developer, but I think we still use ADAL and the https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-with-username-and-password to get to the token we use in the httpClient request.
