### ISSUE TITLE
Error Response 400

### ISSUE THREAD

**Issue by mallen1925** [lithnet/resourcemanagement-webservice#27]
hi,
I'm trying to get this setup and it looks like it works because i get the help page. When me or my colleagues try to connect we get this error. We get it in the browser and in doing a curl. See below

error response 400 : Bad Request
Cache-Control: private
Content Type: application/json; charset=utf-8
Server: Microsoft-iis/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP .NET
Date:
Content-Length: 155

{"ExceptionType":"ArgumentException","Message":"The provided URI scheme 'https' is invalid; expected 'http'.\u000d\u000aParameter name: via","Reason":null} 

Any help on this would be great.

**Comment by ryannewington** [comment]
In step 10, did you accidentally set HTTPS instead of HTTP in your fim service address?


https://github.com/lithnet/resourcemanagement-webservice/wiki/installing-the-web-service

**Comment by mallen1925** [comment]
That was it. I also had the wrong web address in there. I put the MIMservce url. Thank you for the assistance.
