### ISSUE TITLE
Any examples query's on search for resource with wild card? 

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-webservice#30]
Hello,

MIM Portal has a wild card search function with % for any object in that particular object type. For example, if I search for a security group with '%read' it will show all the security group's names have read in it. Technically the same search function should be available in the API call also, I been trying to come up with a query referring your documentation but can't figure out the correct one, below are the example query I came up with:

/v2/resources/?filter=/ManagementPolicyRule%5BDisplayName%3D%27%25FIMMA%27%5D
                      or 
/v2/resources/?filter=/ManagementPolicyRule[DisplayName='%FIMMA'] 

Can you please suggest me with a correct query using a wild card.

Appreciate your help.

**Comment by ryannewington** [comment]
Hi,

You need to do some research on FIM Xpath dialect. The filter parameter in the API call simply passes the xpath query to the FIM service to resolve. The FIM portal works in the same way, it uses xpath queries.

I'd start with the official Microsoft documentation on XPATH https://docs.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652287(v=vs.100) 

But there are plenty of examples around to use once you have the basics worked out. Here's some I've put together https://github.com/lithnet/resourcemanagement-powershell/wiki/XPath%20expression%20examples

**Comment by kongarasri** [comment]
Thank Ryan, the XPath expression examples are so helpful. Appreciate your help.
