### ISSUE TITLE
Kerberos Authentication / Constrained Delegation

### ISSUE THREAD

**Issue by RobinBeismann** [lithnet/resourcemanagement-webservice#31]
Hello,

the install guides only explain Basic Authentication against the webservice, is it also possible to use Kerberos as Authentication against the Webservice and Constrained Delegation against the FIMService/MIMService?

**Comment by KentNordstrom** [comment]
Yes, it's possible and what I use in all my implementations. A few changes in the .config is needed to get it work with KCD.
Off course SPN and Configuration of IIS needs to be in place to get Kerberos working.
I typically use the same IIS Pool Identity as the one I use for MIM Portal. That way KCD setting for FIMService are already configured and working.

But in the .config you basically need two things.
1. A new binding that looks something like.
```
<bindings>
      <webHttpBinding>
        <binding name="windowsAuthBinding">
          <security mode="Transport">
            <transport clientCredentialType="Windows"/>
          </security>
        </binding>
      </webHttpBinding>
</bindings>
```

2. Then in the Endpoint setting point to the new binding

`<endpoint address="https://mimrest.konab.net/v2" behaviorConfiguration="json" binding="webHttpBinding" bindingConfiguration="windowsAuthBinding" name="jsonEP" contract="Lithnet.ResourceManagement.WebService.v2.IResourceManagementWebServicev2"/>`

Hope this helps you get Kerberos and KCD working.

**Comment by RobinBeismann** [comment]
Thanks, worked great - I also used the existing Identity from the MIM Portal App Pool.
I'll close this issue then, thanks again.

**Comment by ryannewington** [comment]
Thanks @KentNordstrom !
