### ISSUE TITLE
Issue with Kerberos on Suburls

### ISSUE THREAD

**Issue by RobinBeismann** [lithnet/resourcemanagement-webservice#32]
Hi both,

again, thanks for the effort on this project, it has helped me a lot.
Right now I'm trying to figure out an issue I experience when I run authenticate from my web app using Kerberos Constrained Delegation to the REST Webservice which uses Kerberos Constrained Delegation against the MIM Service.

I'm doing the Requests using ` Invoke-RestMethod -UseDefaultCredentials [..]` which works fine with GET and POST, but as soon as I try to receive a resource like `$RestServiceURL/v2/resources/$ResourceID` I'm getting a 401 by the REST Webservice while the authentication works fine if I receive something at the level of /v2/resources:
`HTTP Error 401.2 - Unauthorized \n  You are not authorized to view this page due to invalid authentication headers. \n \n \n Most likely causes: \n   \tNo authentication protocol (including anonymous) is selected in IIS. \tOnly integrated authentication is enabled, and a client browser was used that does not support integrated authentication. \tIntegrated authentication is enabled and the request was sent through a proxy that changed the authentication headers before they reach the Web server. \tThe Web server is not configured for anonymous access and a required authorization header was not received. \tThe \"configuration/system.webServer/authorization\" configuration section may be explicitly denying the user access.  \n  \n \n \n Things you can try: \n   \tVerify the authentication setting for the resource and then try requesting the resource using that authentication method.`

This is my web.config for the REST Service: https://gist.github.com/RobinBeismann/6c8809b4eeb6ef4f1b71f92f0e09c738

Do you have any idea?

**Comment by RobinBeismann** [comment]
Just to add:
Any URL with `$RestServiceURL/v2/resources/` works fine - filters on that URL also, the issue starts to occur as soon as there is a sub path behind `/resources/`

**Comment by KentNordstrom** [comment]
I'm afraid I have not seen anything similar to that. The problem to check is that you are indeed using Kerberos from the client calling the REST endpoint. If for some reason the client has started with NTLM you could potentially see something like this.
Use KLIST to verify the client has indeed a proper Kerberos token it can use.

I also notice that in your config file you have not defined the address of the edpoints.... Not sure if it matters, but maybe...
like <endpoint address="https://mimrest.iam.comany.com/v2"

**Comment by KentNordstrom** [comment]
And just to be clear. I guess you have anonymized your config file since the FIMService URL is a bit odd...
`<lithnetResourceManagementClient resourceManagementServiceBaseAddress="http://serviceurl:5725" />`

Where is in fact looks like...
`<lithnetResourceManagementClient resourceManagementServiceBaseAddress="http://fimservice.iam.company.com:5725"/>`

**Comment by RobinBeismann** [comment]
Thanks for the fast reply!
I just "solved" it myself due to https://github.com/dotnet/runtime/pull/46897 I had to build my Invoke-RestMethod Headers myself like this:

```
$hostnameHeader = 'hostname'
$hostname = 'ip'

$params = @{}
$params.Method = $Method
$params.Uri = "https://$hostname/$URL"
$params.Headers = @{ 
	host=$hostnameHeader 
} 
$params.UseDefaultCredentials = $true
$params.ContentType = "application/json"

if($Body){
	$params.Body = ($Body | ConvertTo-Json)
}

Invoke-RestMethod @params

```

However this broke the actual request for urls below /v2/resource/ - not sure why yet.
Apparently the .NET Core Team fixed this in .NET Core 6 and .NET Core 5.0.3, while PowerShell Core 7.1.2 (latest stable) is build on .NET Core 5.0.103.
I've just temporary upgraded to PowerShell Core v7.2.0-preview.3 which uses .NET Core 6.0 until the general version is updated to .NET Core 5.0.3 or the fix is backported to an older .NET Core version..

**Comment by RobinBeismann** [comment]
Just as heads up, Powershell Core 7.1.3 which just came out is based on .NET Core 5.0.4, this should address the issue.
