### ISSUE TITLE
Sending in DateTime as string and other formats

### ISSUE THREAD

**Issue by MostafaHassan** [lithnet/resourcemanagement-webservice#34]
Hi
I am trying to create a resource and send in a DateTime. I have tried different formats and I can't get them to work.
Is there a special format that it needs to be in, or is it a bug?

I get back status code 500, with the following error message:
{
    "error": {
        "code": "internal-server-error",
        "details": null,
        "message": "String was not recognized as a valid DateTime."
    }
}

Some values that I have tried:
"2022-02-11"
'8/18/2018 12:00:00 AM'
'8/1/2018 12:00:00 AM'
'8/18/2018 12:00:00 AM'
'2/22/2018 7:22:16 AM'
'2/22/2018 7:00:00 PM'
'2018-08-18T07:22:16.0000000Z'
'2018-08-18T07:22:16.0000000-07:00'
'Sat, 18 Aug 2018 07:22:16 GMT'
'08/18/2018 07:22:16 -5:00'

I have also tried different time stamps.

Can you help?

**Comment by moshas1** [comment]
Yes, and serializing a DateTime does not help as well. 

DateTime dt = DateTime.Parse("2022-02-11");
var date = JsonConvert.SerializeObject(dt);

Setting an attribute to the value of date gives the error "String was not recognized as a valid DateTime."

**Comment by ryannewington** [comment]
You were very close

MIM expects dates to be in the following format, and always in UTC time

`yyyy-MM-ddThh:mm:ss.000`

**Comment by MostafaHassan** [comment]
It worked, thanks @ryannewington, you have done a good job with this service!
