### ISSUE TITLE
Is it possible to run the application pool by a specific proxy account instead ASP .NET v4.0 classic?

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-webservice#36]
While tuning the Symantec Endpoint Protection policy on our server to support a change we are doing, we ran into a scenario where the call from the lithnet web service is coming from the IIS user account like below:

Hostname:    
Host Address:    
Username:    IIS APPPOOL\.NET v4.5 Classic
Agent Version:    6.9.1.507
OS Type:    windows
OS Version:    Server 2016
Post Date:    Fri Jun 24 2022 12:18:50 GMT-0400 (Eastern Daylight Time)
Post Delay:         00:00:01
Description:    
Policy Name:    
Process:    C:\WINDOWS\SYSTEM32\INETSRV\W3WP.EXE
Module:    C:\Windows\assembly\NativeImages_v4.0.30319_64\System\5455882295d673bbc3a623bb91c8a1ba\System.ni.dll
Disposition:    Connect
Sandbox:    
Operation:    Network Access

Per our organization policy, the request should come from a valid proxy account to tune the Symantec Endpoint Protection policy's on our server. I tried changing the application pool to run with a proxy account, which broke the lithnet webservice API on our server. Just wondering, is it possible to run the application pool with a specific proxy account instead ASP .NET v4.0 classic?

Appreciate the response, and thanks for the great work with the Lithnet FIM/MIM web service API.

**Comment by ryannewington** [comment]
I don't think it matters what account you run it under, but you need to make sure its in 'classic' pipeline mode. The default is 'integrated' and that will not work.

![image](https://user-images.githubusercontent.com/17229877/175751268-d14f86bc-c5c6-4486-abc3-632945f46fe7.png)

**Comment by kongarasri** [comment]
That worked, thanks for the quick response!
