### ISSUE TITLE
While updating value of multivalued filed using Lithnet API on MIM portal, it is overriding the previous value

### ISSUE THREAD

**Issue by shailendra3009** [lithnet/resourcemanagement-webservice#39]
Hello Team,

I was exploring the Lithnet API and here I found that while updating the multivalued attribute on MIM portal, it is not appending the value to the already existing value instead it is overriding the value.

can you please tell me if there is any different way to append value to multivalued attribute instead of overriding using Lithnet API.

Thanks,
Shailendra Mishra

**Comment by KentNordstrom** [comment]
When working with MultiValue attributes you need to work with Add/Delete values if you do not want to "replace" the property.
Read at https://github.com/lithnet/resourcemanagement-webservice/wiki/Add-a-value-to-a-specific-attribute-of-a-resource and https://github.com/lithnet/resourcemanagement-webservice/wiki/Delete-a-value-from-a-specific-attribute-of-a-resource
