### ISSUE TITLE
Status code 500 returned on Denied requests in v2

### ISSUE THREAD

**Issue by KentNordstrom** [lithnet/resourcemanagement-webservice#7]
Using build 2.0.6170.38280

A successful but denied request in MIM returnes status code 500.
In IIS log it looks like...
2016-12-06 06:45:19 172.19.0.10 PATCH /v2/resources/38bbff98-bd9d-4aab-a027-d5dd0d7c0a55/ - 80 DEV-U038173@company.com 172.19.0.10 - - 500 0 0 2687

In MIM it is showing status "Denied" and no special entries in Event Viewer apart from the expected "PermissionDeniedException".

When trying to reproduce I cannot reproduce for "all" types of Denies, so this could be related to this specific request. I will ask dev guys to give me copy of JSON body to add to this issue as information. I suspect something wrong in the body, but if the body is malformed, the request should fail before being submitted to MIM.

**Comment by KentNordstrom** [comment]
I have now verified this issue. If there is no MPR allowing the Request the PATCH does return 500.
It looks to be related to requests where there is NO MPR hit what so ever in the Request.

I see the following in the response body.
{"error":{"code":"interal-server-error","details":null,"message":"Failure message: \u000aAttributes: Brand\u000aSource: ManagementPolicyRule\u000a Additional details: No policy grants the Requestor permission to complete all changes.\u000aCorrelation ID:2dfdb64d-7455-4f1c-be73-e00fcdff4574"}}

**Comment by KentNordstrom** [comment]
I see the same issue if I try the v1 interface with PUT.
In v1 I get 400 response code but the same response message

{"CorrelationID":"fb9dc94a-4948-4d36-bc39-9e0552539b2b","ExceptionType":"PermissionDeniedException","Message":"Failure message: \u000aAttributes: Brand\u000aSource: ManagementPolicyRule\u000a Additional details: No policy grants the Requestor permission to complete all changes.\u000aCorrelation ID:fb9dc94a-4948-4d36-bc39-9e0552539b2b","Reason":null}

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/resourcemanagement-webservice/releases/tag/v2.0.6185
