### ISSUE TITLE
Help! How do I sign (or ignore) the SwaggerWCF error

### ISSUE THREAD

**Issue by adamjbradley** [lithnet/resourcemanagement-webservice#9]
"C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /a /t http://time.certum.pl /v /debug SwaggerWcf.dll

returns the following error
---snip---
After EKU filter, 3 certs were left.
After expiry filter, 3 certs were left.
After Private Key filter, 0 certs were left.
SignTool Error: No certificates were found that met all the given criteria.
---snip---

Gah! Thanks in advance.
//Adam

**Comment by ryannewington** [comment]
Hi Adam,

Sorry for the delay in getting back to you.

The signing is failing because you don't have a private key to sign with. Do you need to sign the swagger DLL for a particular reason?

Ryan

**Comment by ryannewington** [comment]
@adamjbradley did you still need assistance with this one Adam?

**Comment by adamjbradley** [comment]
Sorted! Signed it myself :)
